### PR TITLE
Feature search

### PR DESCRIPTION
**Pull request by rowheat02**

### CODE REVIEW

**Comment by rowheat02** [comment]
For #182
- In add_geojson function geojson is added in layer_group.
- Default feature search property_name- ```name```
- can update the search field for feature ```m.update_search_control(property_name='type')```
- different func for search by location  ```m.add_location_search_control()```
- Tried but could not able make same control for both location and feature search

**Comment by rowheat02** [comment]
For #182
- In add_geojson function geojson is added in layer_group.
- Default feature search property_name- ```name```
- can update the search field for feature ```m.update_search_control(property_name='type')```
- different func for search by location  ```m.add_location_search_control()```
- Tried but could not able make same control for both location and feature search

**Comment by rowheat02** [comment]
https://user-images.githubusercontent.com/40065760/150175883-2d448c08-88a8-468b-bf1d-c1dcdc400a43.mp4

**Comment by giswqs** [comment]
Awesome work! It can benefit from some improvement. Currently, it is throwing an error when creating the map

image

**Comment by rowheat02** [comment]
In my machine, I am not getting such errors. ``` existing_layer ```  must be none and line 329 should not be executed. 
Did you try restarting the kernel ?

**Comment by giswqs** [comment]
Open binder https://gishub.org/leafmap-binder, create a new notebook, install your pull request using the following line, then create a map, you will see the error

```
!pip install --user git+https://github.com/giswqs/leafmap.git@967366c0bf6c37fd133da81855b4852cb9ca7b67
```
image

**Comment by rowheat02** [comment]
Thank you !
Got the same strange error. To debug, can we edit code in Binding itself? or do I need to pull every pushed commit.

**Comment by giswqs** [comment]
Binder is not well suited for editing and debugging. You need to do it locally. Try creating a new conda env and install you local leafmap version using the line below. It will always use the latest version. No need to install every time. 

```
pip install -e .
```

**Comment by rowheat02** [comment]
No such errors in my local :(

**Comment by rowheat02** [comment]
I checked again with the new commit, it is working now. 
image

**Comment by giswqs** [comment]
Merging this PR for now. I will make some improvement later.

**Pull request merged**
