### PR TITLE
Use getattr instead of eval

### PR DESCRIPTION
**Pull request by Piphi5**
`getattr` is more robust and cleaner than trying to use eval for getting parameters

### CODE REVIEW

**Comment by giswqs** [comment]
It seems `get_attr` does not exist. Should it be `getattr`?

**Comment by Piphi5** [comment]
Yeah it is, my bad.

**Comment by giswqs** [comment]
It is still failing. I am not sure if they are caused by the tests only or `getattr` changes result in failed tests. Can you fix it?

**Comment by Piphi5** [comment]
Yeah I'll look into it. It seems like trying to call `"OpenStreetMap.Mapnik"` as a single parameter may be the main issue

**Comment by giswqs** [comment]
It is improving. Only `test_add_circle_markers_from_xy` is failing.

**Comment by Piphi5** [comment]
Is there any reason why this:
```
out_str = m.to_html()
assert "World Cities" in out_str
 ```

would fail with `add_circle_markers_from_xy` but not fail with `add_xy_data`?

**Comment by giswqs** [comment]
It should be `name` rather than `layer_name`. It seems `add_circle_markers_from_xy` is not producing the expected results. There is only one circle plotted on the map. It seems there is a bug with this function, but it might not be related to your commits. 

```python
import leafmap
import ipyleaflet

m = leafmap.Map()
in_csv = "https://raw.githubusercontent.com/giswqs/data/main/world/world_cities.csv"

m.add_circle_markers_from_xy(
    in_csv, x="longitude", y="latitude", name="World Cities"
)
m.add_control(ipyleaflet.LayersControl(position="topright"))
m
```
image

**Comment by Piphi5** [comment]
is the add_circle bug reproducable without the code in this pr?

**Comment by giswqs** [comment]
It is a bug of the ipyleaflet backend. Works fine with folium.

**Pull request merged**
