### PR TITLE
Added support for gradio

### PR DESCRIPTION
**Pull request by giswqs**
This PR adds support for Gradio. #362 
Reference: https://gradio.app/plot-component-for-maps/

```python
import gradio as gr
import leafmap.foliumap as leafmap

def test(x):

    m = leafmap.Map(height='700px')
    url = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'
    url2 = 'https://opendata.digitalglobe.com/events/california-fire-2020/post-event/2020-08-14/pine-gulch-fire20/10300100AAC8DD00.tif'
    m.split_map(left_layer=url, right_layer=url2)
    return m.to_gradio(height='700px')

gr.Interface(test, "text", "html").launch(debug=True)
```

### CODE REVIEW

**Comment by giswqs** [comment]
A plotly map example:

```python
import gradio as gr
import leafmap.plotlymap as leafmap

def create_map(url):
    m = leafmap.Map()
    m.add_cog_layer(url)
    return m   

url = 'https://opendata.digitalglobe.com/events/california-fire-2020/pre-event/2018-02-16/pine-gulch-fire20/1030010076004E00.tif'

demo = gr.Interface(
    fn=create_map,
    inputs=gr.Text(value=url, label='Enter a COG URL'),
    outputs=gr.Plot().style(),
)
demo.launch()
```

https://user-images.githubusercontent.com/5016453/218625821-a4ef18b1-3a47-476f-b95d-d566e2492044.mp4

**Comment by ysig** [comment]
Is it possible to use it to provide input instead of using it to visualize output? It would be great if a user for example could select a point in the map, see https://github.com/gradio-app/gradio/discussions/3492

**Comment by mihow** [comment]
@ysig I am looking for the same functionality: to use the coordinates from a map as input. In our case, for a classification model that uses a geo-prior. Your link to the discussions is no longer available. Was there any helpful guidance there? There is a similar, unanswered question in the huggingface forums: https://discuss.huggingface.co/t/creating-a-leaflet-map-as-input/38315

**Comment by ysig** [comment]
@mihow I managed to do it using streamlit with folium - not sure gradio supports input functionality yet and it's not a problem of leafmap. I suggest that you open an issue at their github so that the demand is more expressed.

**Pull request merged**
