### PR TITLE
Added two functions to add and check styles for different type of geo…

### PR DESCRIPTION
**Pull request by rowheat02**
…metries

Please inform me if any further changes are required.
e.g:
- m.add_geojson_layer('local_geojson_url','layer1','red')
- m.add_geojson_layer('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json','layer2')

### CODE REVIEW

**Review by varun2948 — APPROVED** [review]

**Review by varun2948 — COMMENTED** [review]
I think this code cannot handle the styling of GEOJSON with features of different geometry type.

**Comment by giswqs** [comment]
These two functions can probably be combined as one function `add_geojson()`. My goal is to improve the `add_gdf()` function and then other functions (e.g., `add_geojson()`, `add_shp()`) can build upon the `add_gdf()` function to handle any vector data. 

The current implementation in your `add_geojson` uses the same solid color to fill all geometries. It would be more useful if users can specify a column (either categorical or continuous variable) as color to fill geometries, just like the `add_gdf` function.  

This issue I am having right now is that I can get the `color_continuous_scale` parameter to work for a continuous variable. Ideally, we want to allows create maps like example shown in https://plotly.com/python/mapbox-county-choropleth with only one line of code. 

In short, i think we should focus on improving the `add_gdf` function and make it more robust. Other functions (e.g., `add_geojson()`, `add_shp()`)  can then simply call the `add_gdf()` function under the hood. If you can help getting the `colorscale` parameter to work, that would be greatly appreciated. 

https://github.com/giswqs/leafmap/blob/8bd65d9b42c0629d60b55f194d7e50ec04d9162a/leafmap/plotlymap.py#L611-L622

```python
import leafmap.plotlymap as leafmap
m = leafmap.Map()
url = "https://raw.githubusercontent.com/giswqs/leafmap/master/examples/data/countries.geojson"
m.add_gdf(url, label_col="NAME", color_col="CONTINENT", opacity=0.9)
m
```
image

```python
m.add_gdf(url, label_col="NAME", color_col="POP_EST", opacity=0.5)
```
image

This one is not working properly. `color_continuous_scale` has no effect.
```python
m.add_gdf(url, label_col="NAME", color_col="POP_EST", opacity=0.5, color_continuous_scale="Viridis")
```
image

The `Viridis` color should look like this.

image

**Comment by rowheat02** [comment]
After doing some research and debugging I came with following findings: 

> Fig created from plotly express has correct color_scale but after `self.add_traces(fig.data)` , color_scale was changed to default.

I first checked the fig of px.choropleth_mapbox() , color scale was correct but fig was not showing( no idea why). 
one
But while using the code from [https://plotly.com/python/mapbox-county-choropleth/](url), fig's color scale was correct but adding traces to the map leads to the default color.

**Taking px.choropleth instead of px.choropleth_mapbox**
Fig with correct color_scale
three
 Fig after `self.add_traces(fig.data)` with wrong color Scale
four

### Possible Alternate Solution ( All Features in mapbox Layers):
Since style can be given to each layer of mapbox, all features will be converted to layers and style can be set according to their geometries and properties. For layers control, we can implement the concept of layer Grouping. Unlike plotly express, we should create our custom legend.

**Comment by giswqs** [comment]
Thank you for testing it. That's the same issue I ran into. `fig.show()` can display the colorscale correctly. However, when `fig.data` is passed to `add_traces()`, the colorscale is not carried over. I believe it should be possible to overcome the issue using `go.Choroplethmapbox()`, but the function is a bit complicated. I have not figured it out yet. 
https://plotly.com/python-api-reference/generated/plotly.graph_objects.Choroplethmapbox.html

**Comment by giswqs** [comment]
See the heatmap example. The idea is to use `go.Choroplethmapbox()` without `fig` or `fig.data`. 

https://github.com/giswqs/leafmap/blob/8bd65d9b42c0629d60b55f194d7e50ec04d9162a/leafmap/plotlymap.py#L583-L592

**Comment by rowheat02** [comment]
Yes, use of plotly.graph_objects can help us to overcome this. I also have to explore its usage.
I will let you know if I get any Solution using Graph Object.

**Comment by rowheat02** [comment]
Just Managed to add go.Choroplethmapbbox to the map. But we still have some problem:

- Not able to use geometry field of geodataframe as location parameter.
   ERROR:  <shapely.geometry.polygon.Polygon object at 0x7fcf5ae43ca0> is not JSON serializable
- So I used geojson also with gdf, We can link gdf to geojson by using `featureidkey='properties.{}'.format(label_col)` assuming label_col as unique field. But this can be resolved by rewriting geojson with index id if there are not any unique fields.
- z params only works for continuous value, not for categorical fields
ssss
they are suggesting to use express instead.

Demo:
reds
Viridis

I am still trying to find the fix for the issue ` <shapely.geometry.polygon.Polygon object at 0x7fcf5ae43ca0> is not JSON serializable` while using gdf.geometry in location.

**Comment by giswqs** [comment]
Looks great. I will test it. We can't use `plotly.express` due to the `colorscale` issue.

**Comment by giswqs** [comment]
I just realized that you included a `dem.tif` (14.5 MB) in your commit. I did not catch that when merging the pull request. This make the repo unnecessary large. Please clean up the files before submitting future PR.

**Comment by rowheat02** [comment]
Thank you !! 
That file was created while running the test. Sorry for that :(

**Pull request merged**
