### PR TITLE
USGS The national map API, thin wrapper

### PR DESCRIPTION
**Pull request by karelvancamp**
Already useable, 
in progress,
though not integrated yet (geopandas, in/out).

### CODE REVIEW

**Comment by karelvancamp** [comment]
Done

- Minor possible  improvement is to extract polygon from geopandas rather than bounding box. But don't have GDAL on device i'm working from.

**Comment by karelvancamp** [comment]
Any comments?

**Comment by giswqs** [comment]
Excellent work! There is one typo in the notebook. Can you fix it?

image

**Comment by giswqs** [comment]
The test is still failing. 
https://github.com/giswqs/leafmap/actions/runs/3187974210/jobs/5204088020

**Comment by karelvancamp** [comment]
Ok will check. 

Which linters are applied? Then i can run these on my own before submitting. They pass mine (default pylint)).

**Pull request merged**
