### PR TITLE
Added kwargs width

### PR DESCRIPTION
**Pull request by irrelevantRyan**
This pull request adds kwargs width.

### CODE REVIEW

**Comment by giswqs** [comment]
I purposely did not add the `width` parameter to `kwargs`. The default 100% width of the notebook cell is preferred than the hard-coded width.

**Comment by giswqs** [comment]
Actually, the `width` parameter has no effect. No matter what number you use, the map will always take up 100% width of the cell. This might be bug of the kepler.gl Python package.

**Comment by giswqs** [comment]
See this example. width has no effect. 

```python
from keplergl import KeplerGl
map_1 = KeplerGl(width=200)
map_1
```
image

**Comment by irrelevantRyan** [comment]
I see, interesting. Previously, when I was running leafmap.kepler it would return an Error saying KeyError: 'width'. However, now when I run my program it doesn't happen anymore... which is very odd. It might have been because I had widescreen as False but seeing what you are saying I'm not sure anymore.

**Comment by irrelevantRyan** [comment]
If width is unnecessary I don't see a reason to implement it.

**Comment by giswqs** [comment]
Since the `width` parameter has no effect, I am ok with merging this pull request. I have reported this bug at the kepler.gl repo
https://github.com/keplergl/kepler.gl/issues/1671. If one day Kepler.gl fixes the width bug, I can revert the width back to 100% rather than 600 px.

**Comment by irrelevantRyan** [comment]
Understood, thank you so much for taking the time to review my pull request!

**Comment by giswqs** [comment]
Thank you for the PR. You have become an official contributor to leafmap 🚀

**Pull request merged**
