### PR TITLE
Add support for editing an empty vector dataset interactively

### PR DESCRIPTION
**Pull request by giswqs**
```python
import os
import leafmap
os.environ['MAX_PROPS'] = '20'
m = leafmap.Map()
m
```
Peek 2023-01-31 13-44

### CODE REVIEW

**Comment by PennyJClarke** [comment]
@giswqs Thank you for the video above and updating Leafmap. 

I have since updated my Leafmap version, and retried adding a shapefile, using the same method as the video above, however, the preset column heading are still not populating?

Here is a test shapefile made and exported from QGIS containing three column headings:
image

Here is the video of adding the same exported shapefile to Leafmap and no Keys automatically populate?

https://user-images.githubusercontent.com/93473831/216978833-093b5c0d-b741-43a5-9606-e4661a68ebba.mp4

I am using Leafmap 0.10.5 and ipyleaflet 0.17.0 as I needed to downgrad ipyleaflet for use of the measure tool.

Thank you for your support and guidance.

**Comment by giswqs** [comment]
You need leafmap v.0.16.0 for this feature.

**Comment by PennyJClarke** [comment]
Thank you. 

I used conda install -c conda-forge leafmap and conda install leafmap=0.16.0, using both only offers Leafmap 0.15.0:
image
I removed Leafmap before reinstalling and also tried updating the package, and in both cases 0.15.0 was the newest version offered?

**Comment by giswqs** [comment]
Create a fresh conda env to install leafmap. There might be some Python packages in your existing env that prevent leafmap from being installed.

**Comment by giswqs** [comment]
Try out Google Colab https://colab.research.google.com/notebooks/empty.ipynb

**Comment by PennyJClarke** [comment]
@giswqs thank you for all your support to add this new feature, it is great! I successfully downloaded the new version of Leafmap and the feature works. I see by amending os.environ['MAX_PROPS'] = '20' I can increase the number of rows in the grid, however, beyond 21 I cannot see any additional rows on the screen, even in full screen view. Is it possible to scroll the rows or add a scroll feature to the attribute table? Thank you for your time.

**Pull request merged**
