### PR TITLE
Set toolbar widget visibility with env variables

### PR DESCRIPTION
**Pull request by giswqs**
Users can set environment variables to determine which widget to show on the toolbar. 

```python
import os
import leafmap
os.environ['TIMESLIDER'] = 'FALSE'
os.environ['WHITEBOX'] = 'FALSE'
os.environ['SPLIT_MAP'] = 'FALSE'
m = leafmap.Map()
m
```

```bash
export TIMESLIDER=FALSE
export WHITEBOX=FALSE
export SPLIT_MAP=FALSE
```

### CODE REVIEW

**Comment by giswqs** [comment]
The list of env variable names can be retrieved using `m._ENV_VARS`, 

```text
['ATTRIBUTE_TABLE',
 'BASEMAP',
 'CENSUS',
 'DOWNLOAD_OSM',
 'EDIT_VECTOR',
 'ERASER',
 'INSPECTOR',
 'OAM',
 'OPEN_DATA',
 'PLANET',
 'RASTER',
 'SAVE_MAP',
 'SEARCH_GEOJSON',
 'SEARCH_XYZ',
 'SPLIT_MAP',
 'STAC',
 'TIMESLIDER',
 'WHITEBOX']
```

**Comment by giswqs** [comment]
@abarciauskas-bgse Give it a try and let me know what you think.

**Comment by abarciauskas-bgse** [comment]
Thank you! This looks useful but I was wondering do you think there is a way to configure these widgets upon installation (i.e. some sort of config file) of the library or only through environment variables that are set at runtime?

**Comment by giswqs** [comment]
I am not quite sure what you meant. The installation only installs dependencies, and it does not call any leafmap functions. The map is only displayed at runtime. If you set the env variables at a config file (e.g., `.bashrc`), the widgets will display depending on the env variables.

**Comment by giswqs** [comment]
What would the config file look like? Where would the config file be located? Please provide more specifics if you have something in mind.

**Comment by abarciauskas-bgse** [comment]
Yes, I would have to do more research on whats possible as far as setting some default configuration for a python library. This is great for now. Thank you!

**Pull request merged**
